name: foot_measurement_app
description: SOLOL Foot Measurement App
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  flutter_bloc: ^8.1.5
  path_provider: ^2.1.3
  google_mlkit_pose_detection: ^0.10.0
  image_picker: ^1.0.7
  ffi: ^2.1.2
  cupertino_icons: ^1.0.8       # <-- Mettez cette version
  tflite_flutter: ^0.10.4
  opencv_dart: ^1.0.4
  image: ^4.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ml/yolov8n-seg_float32.tflite
